WINDOWS_SHORTCUTS = {
    "minimize_all": ["win", "m"],
    "show_desktop": ["win", "d"],
    "restore_minimized_windows": ["win", "shift", "m"],
    "open_file_explorer": ["win", "e"],
    "open_feedback_hub": ["win", "f"],
    "virtual_desktop_new": ["win", "ctrl", "d"],
    "virtual_desktop_switch_left": ["win", "ctrl", "left"],
    "virtual_desktop_switch_right": ["win", "ctrl", "right"],
    "virtual_desktop_close": ["win", "ctrl", "f4"],
    "open_settings": ["win", "i"],
    "search": ["win", "s"],
    "lock": ["win", "l"],
    "open_power_user_menu": ["win", "x"],
    "clipboard_history": ["win", "v"],
    "new": ["ctrl", "n"],
    "new_tab": ["ctrl", "t"],
    "close_window": ["ctrl", "w"],
    "focus_address_bar": ["alt", "d"],
    "create_new_folder": ["ctrl", "shift", "n"],
    "open_action_center": ["win", "a"],
    "run_dialog": ["win", "r"],
    "project_screen": ["win", "p"],
    "open_ease_of_access": ["win", "u"],
    "cancel_command": ["ctrl", "c"],
    "paste": ["ctrl", "v"],
    "recall_previous_command": ["up"],
    "copy": ["ctrl", "c"],
    "cut": ["ctrl", "x"],
    "undo": ["ctrl", "z"],
    "redo": ["ctrl", "y"],
    "focus_taskbar": ["win", "t"],
    "focus_system_tray": ["win", "b"],
    "alt_tab": ["alt", "tab"],
    "close_window_alt": ["alt", "f4"],
    "open_properties": ["alt", "enter"],
    "select_all": ["ctrl", "a"],
    "print": ["ctrl", "p"],
    "find": ["ctrl", "f"],
    "open_copilot": ["win", "c"],
    "copilot_navigate_options": ["tab"],
    "copilot_navigate_arrows": ["arrow_keys"],
    "copilot_select": ["enter"],
    "copilot_close": ["esc"],
    "open_copilot_search": ["ctrl", "shift", "s"],
    "toggle_copilot": ["win", "c"],
    
    # Chrome Browser Shortcuts
    "chrome_new_window": ["ctrl", "n"],
    "chrome_new_incognito_window": ["ctrl", "shift", "n"],
    "chrome_new_tab": ["ctrl", "t"],
    "chrome_reopen_closed_tab": ["ctrl", "shift", "t"],
    "chrome_next_tab": ["ctrl", "tab"],
    "chrome_next_tab_alt": ["ctrl", "pgdn"],
    "chrome_previous_tab": ["ctrl", "shift", "tab"],
    "chrome_previous_tab_alt": ["ctrl", "pgup"],
    "chrome_specific_tab": ["ctrl", "number"],
    "chrome_rightmost_tab": ["ctrl", "9"],
    "chrome_home_page": ["alt", "home"],
    "chrome_history_back": ["alt", "left"],
    "chrome_history_forward": ["alt", "right"],
    "chrome_close_tab": ["ctrl", "w"],
    "chrome_close_tab_alt": ["ctrl", "f4"],
    "chrome_close_window": ["ctrl", "shift", "w"],
    "chrome_close_window_alt": ["alt", "f4"],
    "chrome_minimize_window": ["alt", "space", "n"],
    "chrome_maximize_window": ["alt", "space", "x"],
    "chrome_quit": ["alt", "f", "x"],
    "chrome_move_tab_right": ["ctrl", "shift", "pgdn"],
    "chrome_move_tab_left": ["ctrl", "shift", "pgup"],
    "chrome_fullscreen_on": ["f11"],
    "chrome_fullscreen_off": ["f11"],
    "chrome_fullscreen_off_alt": ["esc"],
    "chrome_tab_group_focus": ["f6"],
    "chrome_tab_group_menu": ["menu"],
    "chrome_tab_group_expand": ["space"],
    "chrome_tab_group_expand_alt": ["enter"],
    "chrome_tab_group_move": ["ctrl", "left"],
    "chrome_tab_group_move_alt": ["ctrl", "right"],
    "chrome_menu": ["alt", "f"],
    "chrome_menu_alt": ["alt", "e"],
    "chrome_bookmarks_bar": ["ctrl", "shift", "b"],
    "chrome_bookmarks_manager": ["ctrl", "shift", "o"],
    "chrome_history": ["ctrl", "h"],
    "chrome_downloads": ["ctrl", "j"],
    "chrome_task_manager": ["shift", "esc"],
    "chrome_toolbar_focus": ["shift", "alt", "t"],
    "chrome_toolbar_focus_right": ["f10"],
    "chrome_dialog_focus": ["f6"],
    "chrome_find": ["ctrl", "f"],
    "chrome_find_alt": ["f3"],
    "chrome_find_next": ["ctrl", "g"],
    "chrome_find_previous": ["ctrl", "shift", "g"],
    "chrome_dev_tools": ["ctrl", "shift", "j"],
    "chrome_dev_tools_alt": ["f12"],
    "chrome_clear_browsing_data": ["ctrl", "shift", "delete"],
    "chrome_help": ["f1"],
    "chrome_switch_user": ["ctrl", "shift", "m"],
    "chrome_feedback": ["alt", "shift", "i"],
    "chrome_caret_browsing": ["f7"],
    "chrome_skip_to_content": ["ctrl", "f6"],
    "chrome_inactive_dialog": ["alt", "shift", "a"],
    "chrome_address_bar": ["ctrl", "l"],
    "chrome_address_bar_alt": ["alt", "d"],
    "chrome_address_bar_alt2": ["f6"],
    "chrome_search": ["ctrl", "k"],
    "chrome_search_alt": ["ctrl", "e"],
    "chrome_print": ["ctrl", "p"],
    "chrome_save_page": ["ctrl", "s"],
    "chrome_reload": ["f5"],
    "chrome_reload_alt": ["ctrl", "r"],
    "chrome_hard_reload": ["shift", "f5"],
    "chrome_hard_reload_alt": ["ctrl", "shift", "r"],
    "chrome_stop_loading": ["esc"],
    "chrome_open_file": ["ctrl", "o"],
    "chrome_view_source": ["ctrl", "u"],
    "chrome_bookmark_page": ["ctrl", "d"],
    "chrome_bookmark_all_tabs": ["ctrl", "shift", "d"],
    "chrome_zoom_in": ["ctrl", "+"],
    "chrome_zoom_out": ["ctrl", "-"],
    "chrome_zoom_reset": ["ctrl", "0"],
    "chrome_page_down": ["space"],
    "chrome_page_down_alt": ["pgdn"],
    "chrome_page_up": ["shift", "space"],
    "chrome_page_up_alt": ["pgup"],
    "chrome_top_of_page": ["home"],
    "chrome_bottom_of_page": ["end"],
    "chrome_horizontal_scroll": ["shift", "mousewheel"],
    "chrome_previous_word": ["ctrl", "left"],
    "chrome_next_word": ["ctrl", "right"],
    "chrome_delete_previous_word": ["ctrl", "backspace"],
    "chrome_link_new_tab": ["ctrl", "click"],
    "chrome_link_new_tab_switch": ["ctrl", "shift", "click"],
    "chrome_link_new_window": ["shift", "click"],
    "chrome_link_download": ["alt", "click"],
    "chrome_maximize_toggle": ["double_click"],
    "chrome_zoom_in_mouse": ["ctrl", "mousewheel_up"],
    "chrome_zoom_out_mouse": ["ctrl", "mousewheel_down"],
}
